### ISSUE TITLE
First wort hop adjustment too high by a factor of 100

### ISSUE THREAD

**Issue by Copper280z** [Brewtarget/brewtarget#177]
For example, half an ounce of citra in a 5.5 gallon batch with a 60 min boil outputs a reasonable 19.5 IBU, changing that to first wort results in 1,948.2 IBU, which seems high.

![image](https://cloud.githubusercontent.com/assets/6063379/12937530/a546a8b0-cf77-11e5-89d6-89e4750cc0ea.png)
![image](https://cloud.githubusercontent.com/assets/6063379/12937533/b1a0c4a6-cf77-11e5-9a8f-43887c905b02.png)

Edit: I just found the IBU adjustments and they're set to 10,000 for FW and mash. I have not fiddled with these, but I did change units from metric to imperial at the start. Seems like this is just a bad initial config. Also, the units for this adjustment are unclear that it's percent and not a multiplier.

**Comment by rocketman768** [comment]
Thanks!

**Comment by punkrawkgeek** [comment]
Was just wondering if this was still being worked on or not...

**Comment by dpettersson** [comment]
This issue is closed since 2016-02-10. 
I assume that it was solved by that time since @rocketman768 merged and closed it.

May i ask if the problem has returned?

**Comment by jawsdaws** [comment]
Are you running 2.3.0? It looks like this wasn't fixed until 2.3.1.

**Comment by punkrawkgeek** [comment]
@jawsdaws Where do I get 2.3.1?? I've looked everywhere... :\

**Comment by jawsdaws** [comment]
@punkrawkgeek Try here. https://github.com/Brewtarget/brewtarget/releases

**Comment by punkrawkgeek** [comment]
@jawsdaws Uninstalled and reinstalled the newest one. Still the same thing... Any other ideas???

**Comment by jpkilpi** [comment]
I can confirm that the issue is still there in 3.2.1.
