### ISSUE TITLE
Brewtarget misinterprets the mash temperatures: 65,000 C as 65.000,000 C

### ISSUE THREAD

**Issue by Ra-Chipi** [Brewtarget/brewtarget#569]
Hi!
I have problems with the mash temperature. If I put 65 C, brewtarget shows 65,000 C but interprets 65.000,000 C. I've installed the 2.3.1 debian version.
I've tried the windows version with wine and compiling the source code with cmake and all is the same.

If you look at the image below you'll see the Infussion Temp at 1.223,023 C.
![Captura de pantalla de 2021-04-18 20-11-40](https://user-images.githubusercontent.com/82774910/115156043-c074ba00-a082-11eb-8e7f-7b7ced567477.png)

Thanks for all.

**Comment by xzfantom** [comment]
Try download linux distrib from CI here: https://github.com/Brewtarget/brewtarget/actions It's latest Brewtarget version, but not final release yet, so backup your database before updating. Maybe problem is already fixed.

**Comment by mikfire** [comment]
This can also be a problem if your system's language variables aren't set properly. As a rule, we rely on Qt to do the conversions from strings to numbers and back. 

Run `env | grep -i lang`, make sure everything looks appropriate. If it doesn't, try setting that variable to the proper value.

I don't think this is your problem, just based on what I am seeing. But it is an easy thing to check and it may work.

**Comment by Ra-Chipi** [comment]
Hi!
Thanx for your answers.
I've installed the 2.4 version as @xzfantom suggested me but the error persists (in fact I've found a similar error in other places as, for example, in the original gravity rank of the Belgian Golden Strong Ale: 1,070-1095,000 both in versioin 2.3 and 2.4).

And I've run `env | grep -i lang` as @mikfire suggested and everything is OK:
GDM_LANG=es_ES.UTF-8
LANG=es_ES.UTF-8

Again, thanks for your help.

**Comment by Ra-Chipi** [comment]
Yes, it was a great idea. Less than 1 is good if the unis you use are cal/ºC·g. 1 cal/ºC·g is the specific heat of water. Plastics' between 0,2 and 0,6 cal/ºC·g, depending on the kind of plastic (I use a polypropylene bucket as macerator, and the specific heat of polypropylene is between 0,406 and 0,454 cal/ºC·g), the stailess steel's 0,122 cal/ºC·g.
In fact, water has a specific heat very high. Some gases have specific heat higher than water, but we are not going to do a macerator of any gas ;)
