### ISSUE TITLE
Inventory not displaying and crash when try to edit

### ISSUE THREAD

**Issue by Brew1984** [Brewtarget/brewtarget#814]
Updating from 3.011 to 4.02 the inventory is not migrated. Modifying the inventory in 4.02 results in a crash.

**Comment by matty0ung** [comment]
Sorry you're hitting problems.  Looks like I can recreate the crash locally, so will work on that first.  I suspect the inventory migration will be a small fix, but might come back to you for more diagnostic info if need be.

**Comment by matty0ung** [comment]
I have a fix for the crash.  Looking at the other part.  Seems the inventory amount is not being displayed, even when it is in the database.  Will dig into it further this week.

**Comment by matty0ung** [comment]
Should be fixed in [4.0.3](https://github.com/Brewtarget/brewtarget/releases/tag/v4.0.3), but please reopen this issue if not.  As ever, if you find other problems, please don't hesitate to open a new issue.

**Comment by Brew1984** [comment]
Thanks for the update. Unfortunately the inventory still won't upgrade but the good thing is I can now manually enter the values without a crash.

Regards,
Herman

**Comment by matty0ung** [comment]
Ah, hmm.  If you could upload your pre-upgrade DB, I can see if I can work out what the bug in the upgrade process is.

**Comment by matty0ung** [comment]
Many thanks for emailing me your database file.  That enabled me to work out what was going on.  When we migrated the inventories, we weren't taking account of deleted items.  (Mostly when you delete a hop, fermentable etc, it isn't really deleted in the database, just marked as deleted.)  Because of the way we'd done the update, when an inventory amount was shared by a deleted and non-deleted hop/fermentable/etc, it was often getting attached to the deleted on in the new schema.  I've changed it so it always prefers to attach the inventory to an undeleted ingredient if one is available.  Patch in https://github.com/Brewtarget/brewtarget/pull/823, which I'll merge over the weekend if the builds go OK.

NB: The fix won't apply retrospectively.  If you take your current DB away and replace it with the old pre-upgrade one, then the database upgrade will run again with the improved logic, and you should end up with all your inventory amounts in the newly upgraded system.  However, any edits you made after the last database upgrade would be lost.  So, if you made a lot of edits, you might not want to do this.  Instead, we might try to recover your inventory amounts another way.  (They are there in your current database, but attached to deleted ingredients.)  But it might be a bit involved...

**Comment by matty0ung** [comment]
Fix included in [4.0.4](https://github.com/Brewtarget/brewtarget/releases/tag/v4.0.4).
